import {
  notionFetch,
  notionQueryAll,
  BRIEFS_DB_ID,
  getPageTitle,
  getRichText,
  getSelect,
  getDate,
} from "./notion";

export interface Brief {
  id: string;
  title: string;
  briefType: string;
  periodStart: string;
  periodEnd: string;
  generatedBy: string;
  status: string;
  editorialPriority: string;
}

export interface BriefBlock {
  id: string;
  type: string;
  text: string;
  level?: number;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function parseBrief(page: Record<string, any>): Brief {
  const p = page.properties ?? {};
  return {
    id: page.id as string,
    title: getPageTitle(p),
    briefType: getSelect(p, "Brief Type"),
    periodStart: getDate(p, "Period Start"),
    periodEnd: getDate(p, "Period End"),
    generatedBy: getRichText(p, "Generated By") || getSelect(p, "Generated By"),
    status: getSelect(p, "Status"),
    editorialPriority: getRichText(p, "Editorial Priority"),
  };
}

export async function getAllPublicBriefs(): Promise<Brief[]> {
  const pages = await notionQueryAll(BRIEFS_DB_ID, {
    filter: { property: "Visibility", select: { equals: "Public" } },
    sorts: [{ property: "Period Start", direction: "descending" }],
    page_size: 100,
  });
  return pages.map(parseBrief);
}

export async function getLatestBrief(): Promise<Brief | null> {
  const data = await notionFetch(`/databases/${BRIEFS_DB_ID}/query`, {
    filter: {
      and: [
        { property: "Visibility", select: { equals: "Public" } },
        {
          or: [
            { property: "Status", select: { equals: "Final" } },
            { property: "Status", select: { equals: "Draft" } },
          ],
        },
      ],
    },
    sorts: [{ property: "Period Start", direction: "descending" }],
    page_size: 1,
  });
  if (!data?.results?.length) return null;
  return parseBrief(data.results[0]);
}

export async function getBriefById(id: string): Promise<Brief | null> {
  const page = await notionFetch(`/pages/${id}`);
  if (!page) return null;
  return parseBrief(page);
}

export async function getBriefBlocks(pageId: string): Promise<BriefBlock[]> {
  const data = await notionFetch(`/blocks/${pageId}/children`);
  if (!data) return [];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (data.results ?? []).map((block: Record<string, any>): BriefBlock => {
    const type = block.type as string;
    const content = block[type] ?? {};
    const text = (content.rich_text ?? [])
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .map((t: Record<string, any>) => t.plain_text as string)
      .join("");
    const level = type.startsWith("heading_") ? parseInt(type.slice(-1)) : undefined;
    return { id: block.id as string, type, text, level };
  });
}
